endpoints:
  shutdown:
    enabled: true

#Management Configuration
management:
  security:
    enabled: false
  
  port: 9001
  context-path: /management
  
spring:
#  profiles: default
#    active: devH2
#  datasource:
#    driver-class-name: org.h2database.jdbcDriver
#    url: jdbc:h2:mem:dmc
#    username: sa
#    password: sa
    
  mvc:
    favicon:
      enabled: true
  thymeleaf:
#    check-template-location: true
    cache: false
#    prefix: classpath:templates/
#    suffix: .html
    mode: HTML
  
#    encoding: UTF-8
#    content-type: text/html
#    view-names: thymeleaf/*
#    suffix: .html

# Server Port Configuration
server:
  port: 8080
#Access log configuration
  tomcat:
    accesslog:
      enabled: true
    basedir: ../logs
#    accessLogPattern: "%t %s %a %D %r %b"

# Logging Configuration
logging:
#  config: log4j2.xml
  level:
    org.springframework.web: DEBUG
    org.springframework.security: WARN
    org.springframework.data: WARN
    evm.dmc.web: DEBUG
  file: ../logs/dmc-web.log

dmc:
  security:
    admin:
      username: admin
      password: adminpass
  fileroot: userFiles

    

  
#welcome:
#  message: "Hello ID#cat:)!!"
#  
#service:
#  message: Hello Alex